# -*- coding: utf-8 -*-
"""02.2_inventory_abc_reorder_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GEGRdzcuTBN8Ph7jfbvGLH3ttHQeepA
"""

import os
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set visual theme
sns.set_theme(style="whitegrid")

# 1. Download dataset using kagglehub
print("--- DOWNLOADING DATASET VIA KAGGLEHUB ---")
path = kagglehub.dataset_download("harshsingh2209/supply-chain-analysis")

# 2. Path to the CSV file
csv_path = os.path.join(path, "supply_chain_data.csv")

# 3. Load dataset into Pandas
df = pd.read_csv(csv_path)

print("\n--- DATASET LOADED SUCCESSFULLY ---")
print(f"Dataset Shape: {df.shape[0]} Rows | {df.shape[1]} Columns\n")
print(df.head())

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")


print("---Null Values---")
print(df.isnull().sum())

# 1. Total Order Cost
df['total_cost'] = df['manufacturing_costs'] + df['shipping_costs']

# 2. Total Order Profit ($)
df['profit'] = df['revenue_generated'] - df['total_cost']

# 3. Order Profit Margin (%)
df['profit_margin_pct'] = (df['profit'] / df['revenue_generated']) * 100

# 4. Total Lead Time (Days)
df['total_lead_time'] = df['manufacturing_lead_time'] + df['lead_time']



kpi_cols = ['product_type', 'supplier_name', 'transportation_modes', 'total_cost', 'revenue_generated', 'profit_margin_pct', 'total_lead_time']

print(df[kpi_cols].head())

print(f"\nDataset Shape: {df.shape[0]} Rows | {df.shape[1]} Columns")

plt.figure(figsize=(14, 6))


plt.subplot(1, 2, 1)
sns.boxplot(
    data=df,
    x='transportation_modes',
    y='shipping_costs',
  palette='Set2'
)

plt.title("Shipping Costs Distributed By Transport Mode", fontsize=13, fontweight='bold')
plt.xlabel("Transportation Mode", fontsize=11)
plt.ylabel("Shipping Costs", fontsize=11)

plt.subplot(1, 2, 2)
sns.barplot(
    data=df,
      x='transportation_modes',
      y='shipping_times',
   palette='Blues_d',
   errorbar=None
)

plt.title("Average Shipping Time By Transportation Mode", fontsize=13, fontweight='bold')
plt.xlabel("Transportation Mode", fontsize=11)
plt.ylabel("Shipping Time", fontsize=11)

plt.tight_layout()
plt.show()

mode_summary = df.groupby('transportation_modes').agg(
   avg_shipping_cost=('shipping_costs', 'mean'),
   avg_shipping_time=('shipping_times', 'mean'),
   total_revenue=('revenue_generated', 'sum')
).reset_index()

print("Transportation Mode Performance Summary")
print(mode_summary)

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.boxplot(
    data=df,
       x='supplier_name',
       y='defect_rates',
    palette='Reds'
)

plt.title('Defect Rate Distribution across Suppliers', fontsize=13, fontweight='bold')
plt.xlabel('Supplier', fontsize=11)
plt.ylabel('Defect Rate (%)', fontsize=11)


plt.subplot(1, 2, 2)
sns.countplot(
    data=df,
       x='product_type',
      hue='inspection_results',
     palette='Set1'
)

plt.title('Qauntity Inspection Rate By Product Type', fontsize=13, fontweight='bold')
plt.xlabel('Product Type', fontsize=11)
plt.ylabel('Inspection Results', fontsize=11)
plt.legend(title='Inspection Result')

supplier_risk = df.groupby('supplier_name').agg(
    avg_defect_rate=('defect_rates', 'mean'),
    avg_mfg_cost=('manufacturing_costs', 'mean'),
    avg_lead_time=('lead_time', 'mean')
).reset_index()

print("---Supplier Risk Metrics---")
print(supplier_risk)

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.scatterplot(
    data=df,
       x='stock_levels',
       y='order_quantities',
     hue='product_type',
    style='product_type',
       s=100,
    palette='Set1'
)

plt.plot([0, 100], [0, 100], color='red', linestyle='--', label='Stockout Boundary Line')
plt.title('Stock Levels vs. Order Qaunities', fontsize=13, fontweight='bold')
plt.xlabel('Stock Levels', fontsize=11)
plt.ylabel('Order Quantities', fontsize=11)
plt.legend(title='Product Type')

plt.subplot(1, 2, 2)
sns.barplot(
    data=df,
       x='product_type',
       y='revenue_generated',
    palette='viridis',
    estimator=sum,
    errorbar=None
)

plt.title('Total Revenue Generated By Products', fontsize=13, fontweight='bold')
plt.xlabel('Product Type', fontsize=11)
plt.ylabel('Revenue Generated', fontsize=11)

plt.tight_layout()
plt.show()

df['stock_risk'] = df['order_quantities'] > df['stock_levels']

stockout_summary = df.groupby('product_type').agg(
    total_orders=('order_quantities', 'count'),
    stockout_risk_count=('stock_risk', 'sum'),
    total_revenue=('revenue_generated', 'sum')
).reset_index()

stockout_summary['stockout_risk_ratio %'] = (stockout_summary['stockout_risk_count'] / stockout_summary['total_orders']) * 100

print("---INVENTORY STOCKOUT & REVENUE RISK SUMMARY---")
print(stockout_summary)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

df['target_stockout'] = (df['order_quantities'] > df['stock_levels']).astype(int)

feature_cols = [
    'price',
    'order_quantities',
    'lead_times',
    'manufacturing_costs',
    'defect_rates',
    'shipping_costs',
    'shipping_times'
]

X = df[feature_cols]
y = df['target_stockout']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = RandomForestClassifier(n_estimators =100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(f"Accuracy Score: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")

print(classification_report(y_test, y_pred))

importance_df = pd.DataFrame({
    'Feature': feature_cols,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 5))
sns.barplot(data=importance_df, x='Importance', y='Feature', palette='crest')
plt.title('Feature Importance: Drivers of Stockout Risk', fontsize=13, fontweight='bold')
plt.xlabel('Importance Score', fontsize=11)
plt.ylabel('Feature', fontsize=11)
plt.tight_layout()
plt.show()


df['lead_time_demand'] = df['order_quantities'] * df['lead_times']

df['target_stockout'] = (df['order_quantities'] > df['stock_levels']).astype(int)


df_encoded = pd.get_dummies(df, columns=['product_type', 'transportation_modes'], drop_first=True)

feature_cols = [
    'price', 'order_quantities', 'lead_times', 'manufacturing_costs',
    'defect_rates', 'shipping_costs', 'shipping_times',
    'lead_time_demand'
] + [col for col in df_encoded.columns if col.startswith(('product_type_', 'transportation_modes_'))]

X = df_encoded[feature_cols]
y = df_encoded['target_stockout']





X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=4,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("--- IMPROVED MODEL ACCURACY & PERFORMANCE ---")
print(f"New Accuracy Score: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test, y_pred))


importance_df = pd.DataFrame({
    'Feature': feature_cols,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(data=importance_df.head(10), x='Importance', y='Feature', palette='viridis')
plt.title('Top 10 Feature Importance: Improved Drivers of Stockout Risk', fontsize=13, fontweight='bold')
plt.xlabel('Importance Score', fontsize=11)
plt.ylabel('Feature', fontsize=11)
plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')