# -*- coding: utf-8 -*-
"""Portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqlBG2DjLOmPPKofBWY3rAdeuIoQEDYc
"""

import pandas as pd
import numpy as np
import kagglehub
import os

path = kagglehub.dataset_download("harshsingh2209/supply-chain-analysis")

csv_path = os.path.join(path, "supply_chain_data.csv")

df = pd.read_csv(csv_path)

print("Dataset Shape:", df.shape)
print(df.head())

# 1. Calculate Average Daily Sales (assuming 30-day window)
df['Avg_Daily_Sales'] = df['Order quantities'] / 30

# 2. Calculate Safety Stock (3-day buffer, rounded up)
df['Safety_Stock'] = np.ceil(df['Avg_Daily_Sales'] * 3)

# 3. Calculate Reorder Point
df['Reorder_Point'] = np.ceil((df['Avg_Daily_Sales'] * df['Lead times']) + df['Safety_Stock'])

# 4. Create Reorder Alert (True/False boolean)
df['Reorder_Alert'] = df['Stock levels'] < df['Reorder_Point']

# 5. Filter items needing immediate reorder
reorder_needed = df[df['Reorder_Alert'] == True][['SKU', 'Stock levels', 'Reorder_Point', 'Safety_Stock', 'Lead times', 'Avg_Daily_Sales', 'Reorder_Alert']]

print(f"Total SKUs needing immediate reorder: {len(reorder_needed)}")
reorder_needed.head(10)

df['Total_Revenue'] = df['Price'] * df['Order quantities']

df['Cum_Revenue'] = df['Total_Revenue'].cumsum()
df['Cum_Percen'] = (df['Cum_Revenue'] / df['Total_Revenue'].sum()) * 100

def assign_abc(perc):
    if perc <= 80:
        return 'A'
    elif perc <= 95:
        return 'B'
    else:
        return 'C'

df['ABC_class'] = df['Cum_Percen'].apply(assign_abc)

print(df['ABC_class'].value_counts())

df[['SKU', 'Price', 'Order quantities', 'Total_Revenue', 'Cum_Percen', 'ABC_class']].head(10)

critical_reorders = df[df['Reorder_Alert'] == True][['SKU', 'ABC_class', 'Reorder_Point', 'Total_Revenue']]

print("---URGENT REORDER CLASS---")
print(critical_reorders['ABC_class'].value_counts())

critical_reorders[df['ABC_class'] == 'A'].head(10)